debezium:
  enabled: true
  nameOverride: reporting-debezium
  kafkaInstallationName: '{{ .Release.Name }}-kafka'
  kafkaBootstrapServers: '{{ tpl .Values.kafkaInstallationName $ }}:9092'

opensearch-kafka-connector:
  enabled: true
  nameOverride: reporting-os-kafka-connector
  kafkaInstallationName: '{{ .Release.Name }}-kafka'
  kafkaBootstrapServers: '{{ tpl .Values.kafkaInstallationName $ }}:9092'
